language: php

php:
  - 5.3
  - 5.6

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
